my_string = input('Введите строку и я посчитаю количество символов ')
number_of_symbols = len(my_string)
print('В вашей строке', number_of_symbols, 'символов')
print(my_string.upper())
print(my_string.lower())
print(my_string.replace(' ', ''))
print(my_string[0])
print(my_string[-1])